### ISSUE TITLE
images in embeds not resized

### ISSUE THREAD

**Issue by Andre601** [widgetbot-io/embed#1]
Embeds that have an image (or only have an image) doesn't resize the image itself

### Embed on Web (Canary)
![](https://i.imgur.com/fSTgAvmm.png)

### Original Embed
![](https://i.imgur.com/Vb2QbE9m.png)

**Comment by samdenty99** [comment]
83311b1 should fix this

![image](https://user-images.githubusercontent.com/13242392/40011125-bca791b6-579e-11e8-85c6-0b6199e1d8ea.png)
