### ISSUE TITLE
Dynamic Usernames

### ISSUE THREAD

**Issue by exetico** [widgetbot-io/embed#104]
Hi

I would like to see an option for defining the username in the [options](https://docs.widgetbot.io/embed/crate/options/) for the crate-embed. How can i do it?

I'm running it on a webpage, where it will make sense for me, to define the username in the script, instead of a choice by the user :-)

And btw; Thanks for a great solution! I simply love it.

**Comment by advaith1** [comment]
Setting the name is not currently possible but it's planned for the next update.

**Comment by exetico** [comment]
That sounds great :-) Let's hope it will be an option for the "free"-plan 👍

**Comment by exetico** [comment]
@advaith1 - Is there any ETA, and will it be an option for free? (Fx for orginaztions, non-paid online fora's or so?). Cause we arn't going to pay for a feature like that, however, it's a critical feature, to secure just a bit more control over the usernames for the regular users (Sure, it can be manipulated, but still 😁)...

**Comment by Yomanz** [comment]
There are no public ETAs currently.

**Comment by FlamedHotDog** [comment]
I would just want this, and was just about to create this issue, as I saw that this is already created. Anything you can tell about this now?

**Comment by Yomanz** [comment]
> 
> 
> I would just want this, and was just about to create this issue, as I saw that this is already created. Anything you can tell about this now?

If you're talking about a default username for guests, this is part of our patreon tiers.

https://www.patreon.com/widgetbot

**Comment by FlamedHotDog** [comment]
No, not for all users. Just for example in the crate that you can set the username as value. Is that already possible?

**Comment by Yomanz** [comment]
> 
> 
> No, not for all users. Just for example in the crate that you can set the username as value. Is that already possible?

Yes

**Comment by FlamedHotDog** [comment]
But, I dont have so much money, cause I am a student. Mh maybe I need to use another service then. But I liked yours very much, cause of the design.. 😥dont know what I should do. But for 100% I will not pay you 15$ per month as this is more then my pocket money..

**Comment by Yomanz** [comment]
> 
> 
> But, I dont have so much money, cause I am a student. Mh maybe I need to use another service then. But I liked yours very much, cause of the design.. 😥dont know what I should do. But for 100% I will not pay you 15$ per month as this is more then my pocket money..

I'm also a student.
You can set your guest name anyways, it's not a patreon feature.
Settings **everyones** guest username is a patreon-only feature.

**Comment by FlamedHotDog** [comment]
how then?

**Comment by rg9400** [comment]
I am a bit confused here as well. My goal is to **dynamically** set the name based on their username on my site (which can be passed as a variable via Javascript or a proxy header or a number of other ways). 

Is this something that can be done using patreon or the free tier? If not, I think it could be a valuable add-on.

Titan Embeds has a very basic method for doing this. You can just pass the username in the URL as a parameter (similar to passing webAPI parameters), so I can create a dynamic URL for the embed on the page load.

**Comment by Yomanz** [comment]
> 
> 
> I am a bit confused here as well. My goal is to **dynamically** set the name based on their username on my site (which can be passed as a variable via Javascript or a proxy header or a number of other ways).
> 
> Is this something that can be done using patreon or the free tier? If not, I think it could be a valuable add-on.
> 
> Titan Embeds has a very basic method for doing this. You can just pass the username in the URL as a parameter (similar to passing webAPI parameters), so I can create a dynamic URL for the embed on the page load.

I plan to eventually allow it as configuration via the javascript/URL

**Comment by rg9400** [comment]
> I plan to eventually allow it as configuration via the javascript/URL

Awesome, will it be available on the free tier? That might be the thing that pushes me from ditching a self-hosted V1 to V2.

**Comment by Yomanz** [comment]
This feature is implemented in v3 and will be **free**.

I'll close this issue again when v3 is live :)

**Comment by Yomanz** [comment]
v3 is now in alpha and we have made a blog post about this!

https://blog.widgetbot.io/dynamic-usernames/
