### ISSUE TITLE
v2 Widget does not load in SeaMonkey or Pale Moon browsers

### ISSUE THREAD

**Issue by johnb-xp** [widgetbot-io/embed#122]
**Describe the bug**
The widget is stuck on the spinning square loading screen on both of these browsers, which use Firefox / Gecko based engines. This may affect other gecko based browsers with engines a little behind Firefox. V1 did load in these browsers.

SeaMonkey 2.53 is based on Firefox 60, and Pale Moon 28.9.1 is based on Firefox 68.9

**To Reproduce**
1. Install Pale Moon or SeaMonkey.
2. Load a web page with a WidgetBot widget embedded in it, or go directly to the embedded page.
          http://johnbilkey.cf/wjeb/music.html (This is the site I'm developing but this happens on all sites with the widget)

**Expected behavior**
Expect the widget to load properly. This does happen with the latest version of Chrome and Firefox.

**Browser and version**
PaleMoon 28.9.1
SeaMonkey 2.53.1

**Comment by advaith1** [comment]
Looks like there's an issue in the JS Fetch API in those browsers. As they're on old Firefox versions, we probably just have to wait until they update the Firefox version they're based on.

**Comment by Yomanz** [comment]
Waiting on third-parties.
