### ISSUE TITLE
Documentation page is down

### ISSUE THREAD

**Issue by ElhamAryanpur** [widgetbot-io/embed#123]
**Describe the bug**
The Documentation page is down. it sure is up as MD on github repo of docs, but when going on site's docs, it is down! the site itself works!

**To Reproduce**
1. Go to https://docs.widgetbot.io/embed/crate/

**Expected behavior**
Documentation to load

**Browser and version**
Latest Google Chrome Version, Arch Linux, amd64

**Comment by Yomanz** [comment]
The docs are back.
