### ISSUE TITLE
Same user message ungrouping

### ISSUE THREAD

**Issue by Noiknez** [widgetbot-io/embed#124]
**Is your feature request related to a problem? Please describe.**
I use WidgetBot as a tool for multiple news channel in my projet. In discord the message from the same user to publish the news are un-grouped, this way it separate messages with the username and the related time stamp. 

**Describe the solution you'd like**
I want the embed screen to imitate real discord channel same-person message separation.

**Describe alternatives you've considered**
Adding date stamp in every message for multiple news channel, but it is not as clean as in real discord channel.

**Additional context**

What it look like in embed :
![image](https://user-images.githubusercontent.com/20723083/79046005-7276dc00-7c0e-11ea-8b0b-6955a89b7705.png)
What it look like in real discord channel :
![image](https://user-images.githubusercontent.com/20723083/79045991-62f79300-7c0e-11ea-8797-f67ec461ccb8.png)

**Comment by Yomanz** [comment]
This will be fixed in the next release.
