### ISSUE TITLE
Unable to send messages on specific server

### ISSUE THREAD

**Issue by stephenrs** [widgetbot-io/embed#125]
Hi, 

I've done the initial setup, embedding Widgetbot into my site using the iframe approach. Remote messages are received properly by the Widgetbot instance, but when I try to send a message from the iframe instance, I get the following console errors, and the message is not sent:

![Screen Shot 2020-04-11 at 6 50 28 PM](https://user-images.githubusercontent.com/421262/79057316-cb05a380-7c25-11ea-851d-96333c53404f.png)

Any thoughts would be appreciated.

**Comment by Yomanz** [comment]
> 
> 
> Hi,
> 
> I've done the initial setup, embedding Widgetbot into my site using the iframe approach. Remote messages are received properly by the Widgetbot instance, but when I try to send a message from the iframe instance, I get the following console errors, and the message is not sent:
> 
> ![Screen Shot 2020-04-11 at 6 50 28 PM](https://user-images.githubusercontent.com/421262/79057316-cb05a380-7c25-11ea-851d-96333c53404f.png)
> 
> Any thoughts would be appreciated.

Can you send a link, can you also try logging out and logging in.

**Comment by stephenrs** [comment]
Sorry, no link, I'm doing testing in a dev environment, and getting it to a public place would be nontrivial. And yes, I've tried recycling everything including logged in status.

Is it possible that something is not configured properly on my server? Is this a known issue, and/or does anything in that console output suggest any possible causes?

**Comment by advaith1** [comment]
Can you send your WidgetBot code (with all IDs)?

**Comment by stephenrs** [comment]
I'm rendering an iframe inside a div like this:

`<iframe id="somepvtid" src="https://e.widgetbot.io/channels/698348452312121496/698348452790403084" style="height: 100%; width: 100%; border: none;"></iframe>`

**Comment by Yomanz** [comment]
![image](https://user-images.githubusercontent.com/5119107/79083194-9e848100-7d24-11ea-9a3f-5c0eacddfcca.png)
Can you make sure it has MANAGE_WEBHOOKS

**Comment by stephenrs** [comment]
I'm seeing some light...I was inspecting the DOM and realized that a logout/login button on the widget itself was being obscured in my (quickly thrown together) layout. I fixed the layout and cycled that login, and now messages are getting sent. Previously, I was cycling my Discord login

Now I'm seeing websocket connection errors, and some messages are sent/received but don't show up in the widget conversation history, so I don't think I'm all the way there yet.

@Yomanz You might have hit the server while I was making some changes. It looks like MANAGE WEBHOOKS is set properly...

<img width="728" alt="Screen Shot 2020-04-12 at 7 27 30 PM" src="https://user-images.githubusercontent.com/421262/79083404-b4c61900-7cf3-11ea-9afe-518c97fca45a.png">

**Comment by advaith1** [comment]
Make sure that in **channel settings > permissions**, Manage Webhooks is not set to :x: for @ everyone or WidgetBot

**Comment by stephenrs** [comment]
Bidirectional message sending/receiving appears to be working consistently, but I'm having another issue/question, so I'll start a separate ticket. Thanks!
