### ISSUE TITLE
The channel sidebar sometimes doesn't load.

### ISSUE THREAD

**Issue by animekisa2** [widgetbot-io/embed#126]
**Describe the bug**
The channel sidebar sometimes doesn't load.

**To Reproduce**
Steps to reproduce the behavior (Its mostly random):
1. Clear all cache using Application -> Clear storage -> Clear site data (in Chrome)
2. Refresh the page.
3. Keep doing it until the sidebar doesn't load.

**Observed behavior**
While the console shows everything loaded correctly:
https://i.gyazo.com/9614a8d271a9a94c6ea5798019446812.png
The channels aren't displayed at all:
https://i.gyazo.com/f95a3d6a15e07f92e34e0cdb53bf15a0.png

**Browser and version**
Latest Chrome / Win10

**Comment by advaith1** [comment]
is that "expected behavior" actually the observed behavior?

**Comment by Yomanz** [comment]
> 
> 
> is that "expected behavior" actually the observed behavior?

Yes

**Comment by Yomanz** [comment]
I believe this is fixed.
