### ISSUE TITLE
Recent changes broke unpkg

### ISSUE THREAD

**Issue by LoungeKatt** [widgetbot-io/embed#13]
Webpage using widgetbot-io:
`Refused to execute script from 'https://unpkg.com/@widgetbot/html-embed@1.0.5' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

https://unpkg.com/@widgetbot/html-embed@1.0.5:
`Cannot find module "umd/@widgetbot/html-embed.js" in package @widgetbot/html-embed@1.0.5`

It seems there was an issue on the hosting site that is being passed on a MIM type error to static pages, but actually appears to be a missing file in the package.

**Comment by advaith1** [comment]
We don't recommend using WidgetBot through UNPKG. Our official docs site has code that uses jsdelivr, and that's what we recommend now.

**Comment by LoungeKatt** [comment]
@advaith1 Perhaps you should inform the rest of your staff, since they actually do recommend it in the setup guide on Discord.

<img width="720" alt="screen shot 2018-06-26 at 8 36 20 am" src="https://user-images.githubusercontent.com/1173913/41912009-4bb9ec20-791c-11e8-8265-f36f69470917.png">

<img width="720" alt="screen shot 2018-06-26 at 8 36 49 am" src="https://user-images.githubusercontent.com/1173913/41912011-4e7e784a-791c-11e8-89a8-be86a3a76f94.png">

Regardless, it seems a little silly to host a broken endpoint.

**Comment by samdenty99** [comment]
@LoungeKatt The latest version of the package (1.0.5) contains the specified URL

![image](https://user-images.githubusercontent.com/13242392/41936262-921831f0-7984-11e8-95d4-6e28774dbf5b.png)

 Unpkg is not recommended for use in production sites (although it works 90% of the time)

![image](https://user-images.githubusercontent.com/13242392/41936412-04afdf38-7985-11e8-8add-39d385da5cab.png)

The latest documentation can be found at https://docs.widgetbot.io/embed/

**Comment by LoungeKatt** [comment]
@samdenty99 Do you think one of you could redirect some of the time and effort spent stating that unpkg is not recommended to **update the info on Discord**? 
If you can't maintain it in both places, then have Discord redirect to the site. It seems like a *really simple* solution. It seems like a lot of work to avoid it.

As for the issue itself, you have all of the information I obtained from exploring it. I'm just glad this issue happened before I signed up for Patreon or anything like that. Best of luck.

**Comment by advaith1** [comment]
The code examples in #faq have been fixed, I believe the issue was one of the code examples that used unpkg was sent by samdd who was offline, and one was sent by a different moderator.
