### ISSUE TITLE
Messages sent from the widgetbot are delayed

### ISSUE THREAD

**Issue by stephenrs** [widgetbot-io/embed#130]
**Describe the bug**

Messages sent via Discordapp are received by the widgetbot almost instantaneously, and appear in the sender's conversation history right away. However, messages sent from the widgetbot typically experience a 2-3 second delay before reaching the receiving end as well as before they are shown to the sender.

I'm not sure if this is a bug or expected behavior, so I have some questions. This is my first exposure to Discord in general, so please bear with me as I try to more fully understand how all the pieces fit together...

- When messages are sent from widgetbot are they routed through an intermediate server, or are they sent directly to discordapp?
- Is there anything that I can tweak to make message sending go faster from widgetbot?
- Is the delay just the nature of the way webhooks work in this environment, in which case there's nothing that can be done about it?

**To Reproduce**
1. Go to https://e.widgetbot.io/channels/698348452312121496/698348452790403084
2. Log in
3. Send a message
4. Note the timing at both ends

**Expected behavior**

I think it would be a better UX for the sender to see their messages immediately, even if it took a couple seconds to get to the receiver, in the case where the sending delay is unavoidable.

**Browser and version**
Chrome/Mac latest

**Comment by advaith1** [comment]
> When messages are sent from widgetbot are they routed through an intermediate server, or are they sent directly to discordapp?

they go through the WidgetBot server

> Is there anything that I can tweak to make message sending go faster from widgetbot?

no

> Is the delay just the nature of the way webhooks work in this environment, in which case there's nothing that can be done about it?

it's probably just lag on our server

**Comment by Yomanz** [comment]
> I think it would be a better UX for the sender to see their messages immediately, even if it took a couple seconds to get to the receiver, in the case where the sending delay is unavoidable.

We can look into this.

**Comment by stephenrs** [comment]
> > When messages are sent from widgetbot are they routed through an intermediate server, or are they sent directly to discordapp?
> 
> they go through the WidgetBot server
> 
> > Is there anything that I can tweak to make message sending go faster from widgetbot?
> 
> no
> 
> > Is the delay just the nature of the way webhooks work in this environment, in which case there's nothing that can be done about it?
> 
> it's probably just lag on our server

Thanks for the info.

Is there a technical (or other) reason messages need to go through the widgetbot server? It seems to me that it adds unnecessary complexity to the whole setup, or am I missing something?

In other words, why not just send messages directly through discordapp via the API?

**Comment by stephenrs** [comment]
> > I think it would be a better UX for the sender to see their messages immediately, even if it took a couple seconds to get to the receiver, in the case where the sending delay is unavoidable.
> 
> We can look into this.

Great, thanks. I hope you would agree that 2-3 seconds is a relatively long time to wait to see if a typed message was actually recorded, from a usability and user frustration perspective.

**Comment by advaith1** [comment]
> Is there a technical (or other) reason messages need to go through the widgetbot server? It seems to me that it adds unnecessary complexity to the whole setup, or am I missing something?

> In other words, why not just send messages directly through discordapp via the API?

We can't securely send messages directly from the browser; we'd need to expose the token in the frontend which would make it possible for users to get it and then act as the bot or directly spam.

**Comment by Yomanz** [comment]
> 
> 
> > > I think it would be a better UX for the sender to see their messages immediately, even if it took a couple seconds to get to the receiver, in the case where the sending delay is unavoidable.
> > 
> > 
> > We can look into this.
> 
> Great, thanks. I hope you would agree that 2-3 seconds is a relatively long time to wait to see if a typed message was actually recorded, from a usability and user frustration perspective.

Yeah it's something that got pushed to the backburner but it has been reignited and I'll hopefully get it done very soon :)

**Comment by Inirit** [comment]
Any updates regarding this issue? I would love to use widgetbot, but the latency of chat messages is unfortunately a non-starter.

**Comment by Yomanz** [comment]
> Any updates regarding this issue? I would love to use widgetbot, but the latency of chat messages is unfortunately a non-starter.

It'll be fixed in the next big update.
