### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by kolton256** [widgetbot-io/embed#133]
Please Please Please Please Please Please Please Please Please Please add support for electron I plan to make my application for support for a game im making tysm in advance ps advaith is kewl

**Comment by advaith1** [comment]
whats the issue with electrom?

**Comment by Yomanz** [comment]
Please remake this properly.

**Comment by kolton256** [comment]
it doesnt work it opens up in a browser then i click authorize then on
electron it just turns gray

>

**Comment by Yomanz** [comment]
> 
> it doesnt work it opens up in a browser then i click authorize then on electron it just turns gray
> […](#)

Make a **new** issue and include the console please.
