### ISSUE TITLE
eLECTRON

### ISSUE THREAD

**Issue by kolton256** [widgetbot-io/embed#135]
hello people (love what you do) u told me to make a new issue and here it is ok so i go on my app with electron and it works i can SEE msgs not send becouse i have to log in so i log in DOES NOT OPEN IN ANOTHER WINDOW it opens in a tab and there is an error when i look at console 
![image](https://user-images.githubusercontent.com/63267483/80751038-16a9bf80-8af7-11ea-8e70-822dd3a09d17.png)
and yeah ty and have a great day

**Comment by kolton256** [comment]
also happends if u use guestmode

**Comment by Yomanz** [comment]
That's a warning you can ignore.
