### ISSUE TITLE
More informative "sent message" state

### ISSUE THREAD

**Issue by micimize** [widgetbot-io/embed#137]
`sendMessage` [includes an `optimisticResponse`](https://github.com/widgetbot-io/embed/blob/aee35c60c9d3e195e1b79805d5a3276c2c624107/src/hooks/useSendMessage/useSendMessage.ts#L14-L33), but it does not appear to be rendered, as it takes a while to display the sent message in the channel.

I'm guessing this is because of `// TODO: Get the guests info to provide the proper optimistic response`, and is thus a known issue.

**solution / alternatives**: while fixing the `optimisticResponse` and tagging them message with a loading indicator would be ideal, just displaying a loading indicator at all would be valuable.

**Comment by Yomanz** [comment]
This is done in v3.
