### ISSUE TITLE
Exclude channels in the widget.

### ISSUE THREAD

**Issue by Alonely0** [widgetbot-io/embed#139]
Hi, I use widget bot to make a forum in my discord server with the help of another bots that I coded. The problem its that Widget bot displays the admin channels in the widget althougt I removed the permissions of read, write and webhooks, the channel stills displaying on the widget, it only says in the widget that "You don't have permissions", but the widget shows that the channel exist. I'd like to include something to exclude channels from the widget, as if they were not in the server.

**Comment by advaith1** [comment]
Are you logged in to the widget? By default, it only shows channels that `@everyone` in the server can access, unless you are logged in, in which it will show all the channels you and the bot can access.
