### ISSUE TITLE
Make a new guest in 1 browser every hours

### ISSUE THREAD

**Issue by troke12** [widgetbot-io/embed#14]
can you make this? i don't want to clear cache or reset my browser for make new guest in one browser, i think if you put the timer for every new guest would be nice, it's just idea from me i hope you like my idea

**Comment by advaith1** [comment]
@troke12 For feature requests click [here](https://trello.com/c/wRIl5W7u/69-feature-requests-comment-on-this-card) and add a comment.

**Comment by Yomanz** [comment]
Not sure why this would be implemented.

**Comment by troke12** [comment]
i mean how long the Guests cached ?
