### ISSUE TITLE
Publish as a CloudFlare App

### ISSUE THREAD

**Issue by evanspy1** [widgetbot-io/embed#145]
**Is your feature request related to a problem? Please describe.**
Yes, I know some people use website builders like WordPress or Weebly, and it can be hard to embed HTML when using one of these builders.

**Describe the solution you'd like**
If WidgetBot was published as a CloudFlare app, anyone using a website builder could just proxy their site through CloudFlare, install the app, and they would have instant WidgetBot.  This would also be really convenient for people who do custom-developed sites without a templating engine, so they don't have to add the code to every page.

**Describe alternatives you've considered**
Installing the code the normal way.

Here is some more info on CloudFlare Apps:
**What they are:** https://www.cloudflare.com/apps/
**How to develop/submit one:** https://www.cloudflare.com/apps/developer/dashboard
**Documentation:** https://www.cloudflare.com/apps/developer/docs/getting-started

**Comment by Yomanz** [comment]
We have a Cloudflare app for crate which should solve your problem :)

https://www.cloudflare.com/apps/widgetbot-crate
