### ISSUE TITLE
Channel Specific

### ISSUE THREAD

**Issue by Crenshaw1312** [widgetbot-io/embed#147]
**Channel specifics**
It would be nice to be able to do a command like: ??crate ?onlyhere so when it is previewed on the website it will only show one channel so people can't click around and go to different channels. IK it may seem like it's a lower version of just disabling guestmode but, I believe for announcements channels it would be useful
IT would be very useful for Reddit/twitter/twitch/Youtube pages too

**Comment by Yomanz** [comment]
This is available on our patreon, feel free to come to the discord if you have anymore questions.
