### ISSUE TITLE
Default name color is white on white backgrounds

### ISSUE THREAD

**Issue by Lomuspele** [widgetbot-io/embed#155]
**Describe the bug**
So basically' my member has a certain color for their rank, but in the widgebot when someone writes in the chat it will just show as pure white, not as the color their rank is set.

**To Reproduce**

**Expected behavior**
I expected my member to write in the chat and their name to be in the same colour as the rank they have been set.

**Screenshots**
![](https://image.prntscr.com/image/puVvQm41S3aYL4imNEpahw.png)

**Browser and version**
Google chrome, and think any version.

**Additional context**
Could you fix this problem. Thanks in regards.

**Comment by advaith1** [comment]
We cannot make it show the same color as they have in Discord, but it should not show as white if the background is white, it should default to black like in Discord

**Comment by advaith1** [comment]
This seems to have been fixed; it uses your configured primary (text) color as the default name color.
