### ISSUE TITLE
Failed to compile using nodejs v14.15

### ISSUE THREAD

**Issue by sebseb7** [widgetbot-io/embed#160]
**Describe the bug**
```
Failed to compile.
/opt/embed/src/types/type-fixes.ts
(1,10): Module '"../../node_modules/mobx-react/dist"' has no exported member 'IObserverOptions'.
```

**To Reproduce**
```npm run build```

**Comment by advaith1** [comment]
I can't reproduce this (Node v14.15.1):
![image](https://user-images.githubusercontent.com/11778454/99314811-8757c580-2816-11eb-8b75-56fe8782f4db.png)

could you try deleting your node_modules and installing with `yarn`, if you didn't before?
