### ISSUE TITLE
Webhooks not showing as BOT

### ISSUE THREAD

**Issue by H077y** [widgetbot-io/embed#172]
**Is your feature request related to a problem? Please describe.**
Everyone complains a lot about the fact they show up as a bot

**Describe the solution you'd like**
If webhooks showed up as user accounts, people wouldn't have to complain about this through the website. I know there's no way to stop it from being a webhook, but hiding the fact it's a BOT (webhook) in the website will reduce complains significantly

**Describe alternatives you've considered**
No other alternatives other than telling people to suck it up

**Additional context**
Nope

**Comment by Yomanz** [comment]
This is planned in the new release.
It'll be replaced with GUEST rather than BOT.

**Comment by Yomanz** [comment]
This is now in v3
