### ISSUE TITLE
Guest mode not working onload

### ISSUE THREAD

**Issue by BHare1985** [widgetbot-io/embed#173]
**Describe the bug**
When loading the webpage the link to chat isn't in guestmode right away, despite guestmode being enabled.

**To Reproduce**
1. Go to any html-embed tied to a discord server with ??guestmode
2. Click on "Click here to log in and participate in chat" within a few seconds
3. Notice it asks for discord login
4. Close discord login, re-click it
5. Notice it correctly asks for username (guest mode)

**Expected behavior**
Clicking to chat should ask for the username (guest mode) instantly

**Screenshots**
https://b2.cname.cloud/files/2021/01/c-1610755327-Ed.mp4

**Browser and version**
Latest public chrome and firefox

**Comment by aChenForLife** [comment]
how do I turn on guestmode though?

**Comment by jehowell09** [comment]
Second this - how do we turn on guestmode??

**Comment by dustyzero** [comment]
@aChenForLife @jehowell09 say "??guestmode" in the server

**Comment by Yomanz** [comment]
Should be sorted.
