### ISSUE TITLE
Feature Request: Display channels by user rights

### ISSUE THREAD

**Issue by Bruellhusten** [widgetbot-io/embed#182]
Hi, 
right now the bot seems to show everything it has access to. 
I want to use the bot for a site with a deep rights management. 
For that it would be great if the bot by default would only show the @everyone rights and once you link your discord account that it shows channels you have access to. 
I used the crate so far.

**Comment by advaith1** [comment]
not sure why this issue is still open, but the behavior you requested has always been the actual functionality. if you're having an issue with it then you can get support on [our Discord server](https://discord.gg/widgetbot).
