### ISSUE TITLE
Make a working wrapper for Next.js

### ISSUE THREAD

**Issue by AR-Student824** [widgetbot-io/embed#185]
**Is your feature request related to a problem? Please describe.**
There's currently a React wrapper for WidgetBot, but it does not work with Next.js, and I would like to use WidgetBot on my sites.

**Describe the solution you'd like**
The developers making a version of the React wrappers that is compatible with the Next.js framework, because many people use it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by wildflowericecoffee** [comment]
It does work for Next.js, you have to disable SSR
