### ISSUE TITLE
Message Moderation

### ISSUE THREAD

**Issue by FlyingndCoding** [widgetbot-io/embed#196]
Widgetbot is just awesome its mind blowing but then
i think you should do something like blacklist words
like webhooks using widgetbot cant send some words mostly like those abusing words

**Comment by halid96** [comment]
You can use BOTs for this, there are tons of available BOTs that can handle this... You just need to explore and find ... https://top.gg/ is a nice place to start searching...

**Comment by FlyingndCoding** [comment]
Yes I know that but ig WidgetBot also should have

**Comment by Yomanz** [comment]
This isn't something we want to handle currently but might come in the future.
