### ISSUE TITLE
SHA HMAC Validation of Data

### ISSUE THREAD

**Issue by Octolus** [widgetbot-io/embed#204]
I believe there should be a way to secure both avatar, username and other data with HMAC.

That way we can prevent tampering, so the hmac has to be valid and has to be made from our server. Which secures the data transfer between the...

Server <-> Client HTML <-> WidgetBot Server

Server creates HMAC,prints it to client, client forwards it on connection to widgetbot, which confirms it.

**Comment by Yomanz** [comment]
@Octolus We've finished this now, there will be documentation added to the site soon. If you DM me from our Discord Server I can help you get setup with it.
