### ISSUE TITLE
Banning guests

### ISSUE THREAD

**Issue by neon-dev** [widgetbot-io/embed#208]
**Describe the bug**
If guests log out and right back in after they got banned, they get a new user ID, effectively lifting the ban.

**To Reproduce**
1. Guest: Send a message as a guest in the embed
2. Mod: Ban the guest from Discord's context menu
3. Guest: Log out from the embed sidebar and right back in (same or different name)
4. Guest: You can send messages again

**Expected behavior**
The guest user ID should be bound to the session. Also the avatar should be tied to the user ID and not the name.

**Additional context**
Some kind of fingerprinting would be beneficial to make guest bans at least somewhat useful. Alternatively, temporary IP bans could be considered for banning guest accounts (in this case `/ip <user>`, `/banip <ip> <minutes>` and `/bannedips` commands and context menu options would be useful too).
Another idea is to implement a guests-only mode where there is no login/logout button.

**Comment by Yomanz** [comment]
We do have protection against this but it must be broken. I will look into it.

**Comment by neon-dev** [comment]
@Yomanz I've noticed there's an avatar property in the docs. Is it currently fully implemented and what types/sizes of images are allowed? Because in my tests with some *.png files the custom avatar picture is never used.

**Comment by neon-dev** [comment]
@victiondev I tested it with the linked crate example, just changing server+channel ID and replacing the username line with `avatar: 'https://www.wikipedia.org/static/apple-touch/wikipedia.png'`
Also I noticed apollo debug messages in the console. I don't like idea of Discord server info being directly printed to the console

**Comment by Yomanz** [comment]
> @victiondev I tested it with the linked crate example, just changing server+channel ID and replacing the username line with `avatar: 'https://www.wikipedia.org/static/apple-touch/wikipedia.png'` It did not work. Also I noticed apollo debug messages in the console. I don't like idea of Discord server info being directly printed to the console

I've just realized, I don't think that dynamic avatars are in production yet; they're on emerald and not production because I'm trying to fix a blocking but that's stopping me from releaseing.

**Comment by Yomanz** [comment]
This should all be sorted now, please reopen it if there are still issues.
