### ISSUE TITLE
Dev user names shown as commands with channel prefixes

### ISSUE THREAD

**Issue by neon-dev** [widgetbot-io/embed#209]
**Describe the bug**
When entering `/` this command selection opens:
![grafik](https://user-images.githubusercontent.com/1169307/169344819-b1eea135-7872-4a60-80c2-37e9eb44135a.png)

**Expected behavior**
Nothing should happen(?)

**Comment by Yomanz** [comment]
@advaith1 can you remove these.

**Comment by advaith1** [comment]
these were replaced with actual commands a while ago but prod hasn't been updated yet

**Comment by Yomanz** [comment]
> @advaith1 has production still not been updated yet?

This week it will be.
