### ISSUE TITLE
List banned users

### ISSUE THREAD

**Issue by neon-dev** [widgetbot-io/embed#210]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to retrieve the ID of a banned widget user, once their related messages and ban notice got purged.

**Describe the solution you'd like**
Entering `/unban` without parameters could list all banned widget users, including their names, IDs and the date they got banned. Cherry on top would be to also show who banned the user.

**Describe alternatives you've considered**
A new command to list or search for banned users, but I don't think it's necessary.

**Comment by advaith1** [comment]
Hey, thanks for the suggestion! This is now resolved:

- The /unban command now autocomplete the current banned users.
- There is a new /listbans command that lists all of the banned users.

![image](https://user-images.githubusercontent.com/11778454/190951720-0427d47a-d59c-474d-a946-2a44801e9ac2.png)
