### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by LoryPelli** [widgetbot-io/embed#219]
You should update the emerald widget in the website, it says v3.4.4 also if the bot is at v3.5.1. The strange thing is that if you use emerald.widgetbot.io it says v3.4.4 but if you use e.widgetbot.io it says v3.5.1
Why?

**Comment by advaith1** [comment]
This is intentional, we need to do some more things before we ship this update to the Emerald instance. Emerald patrons will get communication about this soon.
