### ISSUE TITLE
Buttons and Menus

### ISSUE THREAD

**Issue by LoryPelli** [widgetbot-io/embed#220]
Please add the support for buttons and menus in the widget

**Comment by advaith1** [comment]
webhooks cannot send interactions, so if we displayed components they would be grayed out and unclickable; would that be useful in some way?

**Comment by LoryPelli** [comment]
idk, there is already something that in discord is clickable and in the widget isn't

**Comment by victiondev** [comment]
These aren't shown in the widget because we're not able to, its a discord limitation as webhooks cant use interactions. And if we did it through the bot user, only one widget user would be able to interact.
