### ISSUE TITLE
Bot message gives blank screen.

### ISSUE THREAD

**Issue by victorgothacked** [widgetbot-io/embed#230]
**Describe the bug**
When a bot in my server sends a message the embed gives a gray screen.

**To Reproduce**
1. Add widgetbot to a server.
2. Make an embed in a channel
3. Make another bot send a message

**Expected behavior**
Just show the message, thats all.

**Screenshots**
![image](https://user-images.githubusercontent.com/108889461/181043093-dd576ef8-e314-4d63-b84e-19ffdab36726.png)

**Browser and version**
Latest version of Widgetbot
Google Chrome | 103.0.5060.134 (Official Build) (64-bit) (cohort: Stable)
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)

**Comment by advaith1** [comment]
I can't reproduce any issues with those steps, do you have more specific repro steps?

**Comment by victorgothacked** [comment]
Sorry my browser was blocking JS XD
