### ISSUE TITLE
Add option to permit user pings 

### ISSUE THREAD

**Issue by ketura** [widgetbot-io/embed#232]
In the situation where I use the discord integration (as a game server browser chat lobby), it would be useful for people in-app to be able to ping users in discord (the reverse would also be nice, tho that's somewhat more difficult when it comes to semi-anonymous guest users).  Obviously there are some situations where this is not a good default, so it would need to be a flag that could be configured in the bot itself.  We have our own ban methods and users need an account to access the screen with discord integration, so we are not concerned with the potential ping abuse (as we can just ban them from the service as we do for any other offense). 

At the very least, it ought to be possible to ping certain roles (preferably in a configurable manner) so mods can be summoned.

**Comment by Yomanz** [comment]
We do allow pings to be enabled for Users, Roles or everyone. We can help you in our discord https://discord.gg/zyqZWr2
