### ISSUE TITLE
Embed thread rather than channel

### ISSUE THREAD

**Issue by Cyanivde** [widgetbot-io/embed#241]
**Is your feature request related to a problem? Please describe.**
I cannot use html-embed to display a Discord thread.

**Describe the solution you'd like**
I'd like to be able to use html-embed to display a Discord _thread_ rather than a normal channel.
Preferably, I'd like to put the thread id in the "channel" parameter.
This makes sense to me, as Discord regards threads similarly to channels, for example when using "Copy Link",
this is a channel - https://discord.com/channels/1002203895793188965/1002203896292319312
this is a thread - https://discord.com/channels/1002203895793188965/1019511479789162536

```
<widgetbot
    server="299881420891881473"
    channel="<--- thread id --->"
    width="800"
    height="600"
></widgetbot>
<script src="https://cdn.jsdelivr.net/npm/@widgetbot/html-embed"></script>
```

**Describe alternatives you've considered**
Unfortunately I must use threads for my channel.

**Additional context**
I have a channel where each conversation takes place in a separate, automatically-created thread.

Thank you so much for considering this :)

**Comment by advaith1** [comment]
You can now set a default thread using the `thread` parameter. Due to our current system we need both the channel and thread ID.

Here's a demo for html-embed: https://codepen.io/advaith1/pen/mdaJzMJ
