### ISSUE TITLE
Support slash commands in widget

### ISSUE THREAD

**Issue by chocobearxo** [widgetbot-io/embed#263]
**Is your feature request related to a problem? Please describe.**
I wouldn't exactly say that. Me personally I just think the support of slash commands in the widget would be awesome for e.g. Bot devs who wants to showcase their bot on their website, which is what I personally would be using it for.

**Describe the solution you'd like**
The ability to use and see slash commands.
In this case I think it'd be even cooler if you could pass in a bot ID which would be optional. This would do so only slash commands from that specific bot would show up.

**Describe alternatives you've considered**
Maybe add support for other types of commands as well.

- Context menus
- Select menus
- Buttons
- Modals

But for starters I think slash commands is the most important.

**Additional context**

**Comment by advaith1** [comment]
Due to Discord limitations this is not possible for us to implement
