### ISSUE TITLE
Remove user tag

### ISSUE THREAD

**Issue by lorypelli** [widgetbot-io/embed#287]
Remove it at the bottom left

**Comment by advaith1** [comment]
0 discriminators were hidden in v3.9.0 b1b665be62f51f472898da9c78d92eefa1b1a0d3

**Comment by lorypelli** [comment]
> 0 discriminators were hidden in v3.9.0 [b1b665b](https://github.com/widgetbot-io/embed/commit/b1b665be62f51f472898da9c78d92eefa1b1a0d3)

Right, I had to do login again
