### ISSUE TITLE
ERROR when fetching Lottie data

### ISSUE THREAD

**Issue by centinaalexa** [widgetbot-io/embed#341]
I have the issue as seen in the screenshot
<img width="532" alt="Screenshot 2023-09-27 at 22 58 03" src="https://github.com/widgetbot-io/embed/assets/108895157/964276f4-c331-4acb-931e-35fa0d85c8a0">

you can reproduce the issue by looking at my website www.sage.blue

Go to the widget bot in left bottom and go to the #welcome channel.

**Comment by advaith1** [comment]
this has been fixed
