### ISSUE TITLE
Custom server invite links

### ISSUE THREAD

**Issue by Andre601** [widgetbot-io/embed#78]
### The suggestion
At the moment does WidgetBot generate an own invite (if it has permissions for it) for the "Join" button and as far as I remember are those invites timed (with expiry).

This is ok, but not everyone wants to have that.
I, for example, want to have one main invite, to track, how many have joined.

So an option, to provide an own invite would be appreciated because with that way you could also easily track, how many people have joined your guild through the widget (when using a separate invite).

### Examples
**Crate**:
```html
<script async src="https://cdn.jsdelivr.net/npm/@widgetbot/crate@3">
  const crate = new Crate({
    server: 'guildID',
    channel: 'channelID',
    <!-- Lets the crate use the provided invite instead of making one -->
    invite: 'https://discord.gg/YourInvite'
  })
</script>
```

**HTML-Embed**:
```html
<widgetbot
  server="guildID"
  channel="channelID"
  id="embed"
  invite="https://discord.gg/YourInvite"
></widgetbot>
<script src="https://cdn.jsdelivr.net/npm/@widgetbot/html-embed"></script>
```

**Comment by advaith1** [comment]
this is done in v2
