### ISSUE TITLE
Sometimes un-reacts don't register (cl3 and fluidsonic, not cl2)

### ISSUE THREAD

**Issue by Andre601** [widgetbot-io/embed#79]
### Issue
There is a weird behaviour with when you add/remove reactions to/from a message.

When you remove a reaction, does the bot/crate not register the change (Still showing the same amount of reactions).
Adding the reaction back lets the crate update the number, by increasing it (f.e. 6 becomes 7, while in reality it's still 6 reactions)
When you then remove the reaction does the crate remove all reactions the message has.
Re-adding lets it re-add those reactions, but still with the wrong number.

### Image
![](https://thumbs.gfycat.com/UnhappyEarnestApisdorsatalaboriosa-size_restricted.gif)

**Comment by advaith1** [comment]
Looks like this only happens sometimes, and only in cluster 3 and the fluidsonic fork. It doesn't happen on cluster 2, and it is unknown if it affects the latest version.

**Comment by Andre601** [comment]
I use a seperate fork/"cluster" from someone else.
I assume it's probably a fork of cluster 3 in that case.

**Comment by advaith1** [comment]
disweb.deploys.io is an instance of the fluidsonic fork.
