### ISSUE TITLE
Hiding crate when clicking the close button

### ISSUE THREAD

**Issue by sebastientromp** [widgetbot-io/embed#8]
Hello,

I would like to hide the Crate widget when the user clicks on the close button, instead of minimizing it.
Is there an event I could listen to that would tell me when the widget is toggled off? I tried

```
		crate.on('toggle', open => {
			console.log('calling toggle', open);
			if (!open) {
				crate.hide();
			}
		})
```
but the log is never called.

Am I doing something wrong?

**Comment by samdenty99** [comment]
@sebastientromp  The `.on` method in V3 only supports events from the [`embed-api`](https://github.com/widgetbot-io/embed-api/blob/143e117ffe7e6060bbef808ca8dc85cffdbef208/src/types.d.ts#L15).

Crate internally now uses Redux, which is exposed as `.store`. Redux allows you to subscribe to state changes, so you should lookup the docs for that.

![image](https://user-images.githubusercontent.com/13242392/41430282-7a52b9ae-7007-11e8-8fc1-1b88a8c6245a.png)

---

Crate provides a CSS API, which would most likely be sufficient in this situation.

```ts
new Crate({
  server: '299881420891881473',
  css: `
    &:not(.open) {
      opacity: 0;
    }
  `
})```

**Comment by sebastientromp** [comment]
The CSS didn't do the trick, but listening to the state changes worked perfectly (and even allowed me do push things a little bit further). Thanks a lot!
