### ISSUE TITLE
Add support for slowmode.

### ISSUE THREAD

**Issue by Andre601** [widgetbot-io/embed#81]
Right now users can send messages through the widget without any slowing down/limitations, due to the nature of webhooks.
That way can they easily bypass the slow mode of discord, which most people probably don't want.
So implementing support for slow mode would be appreciated.

**Comment by Andre601** [comment]
[Insert reason for non-stale here]

**Comment by Yomanz** [comment]
Added in https://github.com/widgetbot-io/embed/releases/tag/v3.5.0
