### ISSUE TITLE
Mentions aren't rendered in embeds

### ISSUE THREAD

**Issue by Andre601** [widgetbot-io/embed#85]
Embeds that contain mentions of users (or channels) aren't formatted.

![](https://i.imgur.com/hQpMHYQ.png)

The mentioned user is clearly on the guild, shown by this image (it also shows my mention as proof).
![](https://i.imgur.com/N1DnLad.png)

**Comment by Andre601** [comment]
This is also the case with pop up messages (Those that are shown in the crate).

**Comment by advaith1** [comment]
That's a different bug, please make a separate issue for that
